config/routes.rb
Rails.application.routes.draw do
  resources :costs
  resources :incomes
  resources :categories
  root 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :costs, :dependent => :destroy
  has_many :incomes, :dependent => :destroy
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        flash[:success] = 'Category was successfully created.'
        format.html { redirect_to @category }
        format.json { render :show, status: :created, location: @category }
      else
        flash[:danger] = 'There was a problem creating the Category'
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        flash[:success] = 'Category was successfully updated.'
        format.html { redirect_to @category }
        format.json { render :show, status: :ok, location: @category }
      else
        flash[:danger] = 'There was a problem updating the Category.'
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      flash[:success] = 'Category was successfully destroyed.'
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        flash[:success] = 'Cost was successfully created.'
        format.html { redirect_to @cost }
        format.json { render :show, status: :created, location: @cost }
      else
        flash[:danger] = 'There was a problem creating the Cost.'
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        flash[:success] = 'Cost was successfully updated.'
        format.html { redirect_to @cost }
        format.json { render :show, status: :ok, location: @cost }
      else
        flash[:danger] = 'There was a problem updating the Cost.'
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      flash[:success] = 'Cost was successfully destroyed.'
      format.html { redirect_to costs_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cost
    @cost = Cost.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cost_params
    params.require(:cost).permit(:amount, :category_id)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        flash[:success] = 'Income was successfully created.'
        format.html { redirect_to @income }
        format.json { render :show, status: :created, location: @income }
      else
        flash[:danger] = 'There was a problem creating the Income.'
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        flash[:success] = 'Income was successfully updated.'
        format.html { redirect_to @income }
        format.json { render :show, status: :ok, location: @income }
      else
        flash[:danger] = 'There was a problem updating the Income.'
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      flash[:success] = 'Income was successfully destroyed.'
      format.html { redirect_to incomes_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_income
    @income = Income.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def income_params
    params.require(:income).permit(:amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Back', categories_path, class: 'btn btn-danger btn-xs' %>

app/views/categories/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View Categories', categories_path %></li>
  <li><%= link_to 'View Costs', costs_path %></li>
  <li><%= link_to 'View Incomes', incomes_path %></li>
</ul>

<h1>Listing Categories</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Costs</th>
    <th>Income</th>
    <th>Total</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{category.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{category.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= category.name %>
          </span>
      </td>
      <td>

        <% if !Cost.where(category_id: category.id).nil? %>
          <%= "-$#{Cost.where(category_id: category.id).sum(:amount)}" %>

          <!-- Modal -->
          <div class="modal fade" id="category-<%= category.id %>-names" tabindex="-1" role="dialog" aria-labelledby="category-<%= category.id %>-label" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="category-<%= category.id %>-label">Name</h4>
                </div>
                <div class="modal-body">
                  <%= category.name %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </td>
      <td>
        <% if !Income.where(category_id: category.id).nil? %>
          <%= "$#{Income.where(category_id: category.id).sum(:amount)}" %>
        <% end %>
      </td>

      <td>
        <% if !Cost.where(category_id: category.id).nil? && !Income.where(category_id: category.id).nil? %>
          <%= "$#{Income.where(category_id: category.id).sum(:amount) - Cost.where(category_id: category.id).sum(:amount)}" %>
        <% end %>
      </td>

      <td><%= link_to 'Show', category, class: 'btn btn-primary btn-xs' %></td>
      <td><%= link_to 'Edit', edit_category_path(category), class: 'btn btn-info btn-xs' %></td>
      <td><%= link_to 'Destroy', category, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn
        btn-danger btn-xs' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to new_category_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Category
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path, class: 'btn btn-danger btn-xs' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-info btn-xs' %> |
<%= link_to 'Back', categories_path, class: 'btn btn-danger btn-xs' %>

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
        <% @cost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <div class="col-sm-10">
      <%= f.number_field :amount, class: 'form-control', required: true  %>
    </div>
  </div>

  <div class="field form-group">

    <div class="col-sm-10">
      <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: 'Select Category'}, class:
                                                  'form-control', required: true ) %>
    </div>
  </div>
  <br/>
  <br/>
  <br/>
  <div class="actions form-group">
    <div class="col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Back', costs_path, class: 'btn btn-danger btn-xs' %>

app/views/costs/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View Categories', categories_path %></li>
  <li class="active"><%= link_to 'View Costs', costs_path %></li>
  <li><%= link_to 'View Incomes', incomes_path %></li>
</ul>

<h1>Listing Costs</h1>

<table class="table">
  <thead>
  <tr>
    <th>Amount</th>
    <th>Category</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @costs.each do |cost| %>
      <tr>
        <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{cost.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{cost.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= "$#{cost.amount}" %>
          </span>
          <% if cost.amount? %>
              <!-- Modal -->
              <div class="modal fade" id="cost-<%= cost.id %>-amounts" tabindex="-1" role="dialog" aria-labelledby="cost-<%= cost.id %>-label" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title" id="cost-<%= cost.id %>-label">Amount</h4>
                    </div>
                    <div class="modal-body">
                      <%= cost.amount %>
                    </div>

                  </div>
                </div>
              </div>
          <% end %>

        </td>
        <td><%= link_to cost.category.name, cost.category %></td>
        <td><%= link_to 'Show', cost, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn
        btn-danger btn-xs' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to new_cost_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New Cost
<% end %>

app/views/costs/new.html.erb
<h1>New Cost</h1>
<br/>
<%= render 'form' %>
<br/>
<br/>
<br/>
<%= link_to 'Back', costs_path, class: 'btn btn-danger btn-xs' %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @cost.category.name %>
</p>
<p>
  <strong>Amount:</strong>
  <%= "$#{@cost.amount}" %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost), class: 'btn btn-info btn-xs' %> |
<%= link_to 'Back', costs_path, class: 'btn btn-danger btn-xs' %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% @income.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <div class="col-sm-10">
      <%= f.number_field :amount, class: 'form-control', required: true %>
    </div>
  </div>

  <div class="field form-group">
    <div class="col-sm-10">
      <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: 'Select Category'}, class:
                                                  'form-control', required: true) %>
    </div>
  </div>

  <br/>
  <br/>
  <br/>
  <div class="actions form-group">
    <div class="col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Back', incomes_path, class: 'btn btn-danger btn-xs' %>

app/views/incomes/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View Categories', categories_path %></li>
  <li><%= link_to 'View Costs', costs_path %></li>
  <li class="active"><%= link_to 'View Incomes', incomes_path %></li>
</ul>


<h1>Listing Incomes</h1>

<table class="table">
  <thead>
  <tr>
    <th>Amount</th>
    <th>Category</th>
    <th colspan="5"></th>
  </tr>
  </thead>

  <tbody>
  <% @incomes.each do |income| %>
    <tr>
      <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{income.created_at.strftime("%m/%e/%Y
           at %w:%M %p")}, Last modified on #{income.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= "$#{income.amount}" %>
          </span>
        <% if income.amount? %>
          <!-- Modal -->
          <div class="modal fade" id="income-<%= income.id %>-amounts" tabindex="-1" role="dialog"
               aria-labelledby="income-<%= income.id %>-label" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="income-<%= income.id %>-label">Amount</h4>
                </div>
                <div class="modal-body">
                  <%= income.amount %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>

      <td><%= link_to income.category.name, income.category %></td>
      <td><%= link_to 'Show', income, class: 'btn btn-primary btn-xs' %></td>
      <td><%= link_to 'Edit', edit_income_path(income), class: 'btn btn-info btn-xs' %></td>
      <td><%= link_to 'Destroy', income, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn
        btn-danger btn-xs' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to new_income_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Income
<% end %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>
<br/>
<br/>
<br/>
<%= link_to 'Back', incomes_path, class: 'btn btn-danger btn-xs' %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @income.category.name %>
</p>
<p>
  <strong>Amount:</strong>
  <%= "$#{@income.amount}" %>
</p>

<%= link_to 'Edit', edit_income_path(@income), class: 'btn btn-info btn-xs' %>  |
<%= link_to 'Back', incomes_path, class: 'btn btn-danger btn-xs' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navigation' %>

<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-12">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: "alert alert-dismissible alert-#{name}" %>
      <% end -%>
    </div>
  </div>
  <div class="row">
    <!--<div class="col-xs-3">-->
    <!--<h3>Tealeaf Academy Todo</h3>-->
    <!--</div>-->
    <div class="col-xs-9">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Wallet App</a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li class="divider"></li>
          <li><%= link_to 'Create a category', new_category_path %></li>
          <li><%= link_to 'Create a cost', new_cost_path %></li>
          <li><%= link_to 'Create a income', new_income_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>